version: "3"
services:
  react_native:
    build: .
    command: ["yarn", "start"]
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.4
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
